use_frameworks!

target 'JetToTheFuture_Example' do
  pod 'JetToTheFuture', :path => '../'

  target 'JetToTheFuture_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
