use_frameworks!

abstract_target 'JetToTheFuture' do
  pod 'JetToTheFuture', :path => '../'

  target 'JetToTheFuture_Example' do
    target 'JetToTheFuture_Tests' do
      inherit! :search_paths

      pod 'Quick'
      pod 'Nimble'
    end
  end

  target 'Example CLI for JetToTheFuture' do
  end
end
